# This is a basic workflow to help you get started with Actions

name: Install KiCad

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install KiCad
        run: |
          choco install --no-progress kicad
          dir "C:\Program Files\KiCad\6.0\bin"
          # which python3
          # echo ${env:PATH}
          $env:PATH = "C:\Program Files\KiCad\6.0\bin;${env:PATH}"
          # echo dir env:
          # python --version
          # dir
          python t1.py
          python -m pip install pip
          # KiCad has pip as module, but not the script!!!
          # which pip
          python -m pip install wheel
          python -m pip install kibot
          which kibot
          cat C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\kibot
          kibot -vvvv --help-outputs
          kibot --version
          dir C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\kibot
          echo C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\kibot
          C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\kibot -vvvv --help-outputs

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
