# This is a basic workflow to help you get started with Actions

name: Install KiCad

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install KiCad
        # The shebang is wrong for power shell and for bash
        # shell: bash
        shell: cmd
        run: |
          @echo "choco install --no-progress kicad"
          choco install --no-progress kicad
          @echo dir "C:\Program Files\KiCad\6.0\bin\Scripts"
          dir "C:\Program Files\KiCad\6.0\bin\Scripts"
#          @echo cmd /k "C:\Program Files\KiCad\6.0\bin\kicad-cmd.bat"
#          cmd /c "C:\Program Files\KiCad\6.0\bin\kicad-cmd.bat"
          @echo KiCad command prompt inlined
          for /f "USEBACKQ" %%a in (`powershell -NoProfile -Command ^(Get-Item "kicad.exe"^).VersionInfo.ProductVersion`) do set kicadVersion=%%a
          @echo ************************************
          @echo * KiCad %kicadVersion% Command Prompt
          @echo ************************************
          set _BIN_DIR=%~dp0
          set _PYTHON_SCRIPTS_DIR=%_BIN_DIR%Scripts
          set PATH=%_BIN_DIR%;%_PYTHON_SCRIPTS_DIR%;%PATH%
          set PYTHONHOME=%_BIN_DIR%
          set PYTHONUTF8=1
          @echo You may now invoke python or pip targeting kicad's install
          cd /d %USERPROFILE%\Documents\KiCad\%kicadVersion%
          set _BIN_DIR=
          set _PYTHON_SCRIPTS_DIR=
          @rem end of KiCad script
          @echo Missing dir: %USERPROFILE%\Documents\KiCad\%kicadVersion%
          @echo kibot --version
          @echo pip install --no-compile kibot
          pip install --no-compile kibot
          @echo pip install lxml
          pip install lxml
          @echo cat "C:\Program Files\KiCad\6.0\bin\Scripts\kibot"
          cat "C:\Program Files\KiCad\6.0\bin\Scripts\kibot"
          kibot --version
#           # dir "C:\Program Files\KiCad\6.0\bin"
#           # dir "C:\Program Files\KiCad\6.0\bin\Lib"
#           # dir "C:\Program Files\KiCad\6.0\bin\scripting"
#           # ls -la "/C/Program Files/KiCad/6.0/bin/Scripts"
#           # which python3
#           cmd /k "C:\Program Files\KiCad\6.0\bin\kicad-cmd.bat"
#           echo ${env:PATH}
#           $env:PATH = "C:\Program Files\KiCad\6.0\bin;C:\Program Files\KiCad\6.0\bin\Scripts;${env:PATH}"
#           # export PATH="/C/Program Files/KiCad/6.0/bin:/C/Program Files/KiCad/6.0/bin/Scripts:$PATH"
#           # echo dir env:
#           # python --version
#           # dir
#           # python t1.py
#           # python -m pip install pip
#           # KiCad has pip as module, but not the script!!!
#           # which pip
#           # python -m pip install wheel
#           pip install --no-compile kibot
#           pip install lxml
#           which kibot
#           # dir "C:\Program Files\KiCad\6.0\bin\Scripts"
#           # dir "C:\Program Files\KiCad\6.0\bin\Lib\site-packages\kibot"
#           # cat C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\kibot
#           cat "C:\Program Files\KiCad\6.0\bin\Scripts\kibot"
#           sed "s/Program Files/program~1/" "C:\Program Files\KiCad\6.0\bin\Scripts\kibot" > "C:\Program Files\KiCad\6.0\bin\Scripts\kibot.ok"
#           Move-Item -force "C:\Program Files\KiCad\6.0\bin\Scripts\kibot.ok" "C:\Program Files\KiCad\6.0\bin\Scripts\kibot"
#           cat "C:\Program Files\KiCad\6.0\bin\Scripts\kibot"
#           kibot --version
#           # The following fails, most probably because the shebang has spaces
#           # kibot -vvvv --help-outputs
#           python "C:\Program Files\KiCad\6.0\bin\Scripts\kibot" -vvvv --help-outputs
#           # kibot --version
#           # dir C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\kibot
#           # echo C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\kibot
#           # C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\kibot -vvvv --help-outputs
#           # C:\Program Files\KiCad\6.0\bin\Scripts\kibot -vvvv --help-outputs

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
